### ISSUE TITLE
Search and replace of ">" and "<" symbols when we are copy and pasting

### ISSUE THREAD

**Issue by Ashersam** [friendsofagape/autographa-lite#98]
![pjimage.jpg](https://images.zenhubusercontent.com/5bfe41d2c933760fceec6ace/45d357c9-6068-4d38-a01f-53fb2147eb35)I have an USFM file that has been drafted form AutographaMT with lots ">>>" and "<<<" symbols. 
I'm able to replace these symbols when I manually type it on the search field, it finds the changes to be done and replaces it. 

But when I copy the same symbol form translation panel and paste search field, it's not able to find any symbols in the file and thus it returns me a file replaced with &gt and &lt instead of <, > symbols

**Comment by vipinpaul** [comment]
This bug occurs even while "comparing the files and also while replacing other words too", While replacing other words, words are being replaced but the symbols (< & >) also replace with &gt and &lt. this issue only occurs while copying from the DOM.

But while copying the word from the console window and paste it in the search field then it replaces the words properly without any error.

Found that the bug might because of HTML element conversion.
So, try adding an HTML parser for avoiding the HTML element conversion in the text, It worked at front-end but still shows the bug at the back-end.
